"""Local validation harness for `bot.py`. Not part of the graded submission.

Run with a Python that supports `StrEnum` (3.11+):

    python3.13 sim.py            # all checks
    python3.13 sim.py theo       # pricer vs Monte Carlo only
    python3.13 sim.py estimate   # parameter recovery only
    python3.13 sim.py session    # trading sessions only
    python3.13 sim.py edge       # degenerate inputs only

Checks, in order:
  1. `price_option_from_parameters` against Monte Carlo paths generated by `MarketParameters`
     itself -- this is what the THEO test scores.
  2. `warm_up` recovering the parameters, and `price_option` tracking the true-parameter price.
  3. Full trading sessions against competing market makers and informed counterparties, with the
     exchange's margin accounting, asserting no exception and no bankruptcy.
  4. Degenerate inputs: no history, a rate pinned at zero, zero-step options that settle a day
     late, huge fill-or-kill orders, a reversed fill-or-kill side convention.
"""

import os as _os
import sys as _sys

_ROOT = _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))
if _ROOT not in _sys.path:
    _sys.path.insert(0, _ROOT)

import math
import random
import sys
from collections import defaultdict
from dataclasses import dataclass, field

from exchange import Account, Rotation, allocate_fok, allocate_rfq, collect_quotes
from bot import (
    AJARAI_UNDERLYING_ID,
    FED_FUNDS_RATE_UNDERLYING_ID,
    THERIODIC_UNDERLYING_ID,
    BinaryOption,
    FokOrder,
    MarketHistory,
    MarketMaker,
    MarketParameters,
    OptionLeg,
    OrderType,
    Quote,
    Underlying,
    _Params,
    _price_with_params,
)

COMPANY_IDS = (AJARAI_UNDERLYING_ID, THERIODIC_UNDERLYING_ID)
ALL_IDS = (FED_FUNDS_RATE_UNDERLYING_ID,) + COMPANY_IDS
# The real grader runs on a $10-$40 balance against contracts worth at most $1, so margin, not
# appetite, is the binding constraint. Anything calibrated at a larger scale misleads badly.
STARTING_CASH = 20.0


def true_price(parameters: "MarketParameters | _Params", values: dict[int, float], option: BinaryOption) -> float:
    # Accepts a `_Params` directly so `real_sim` can hand over the parameters of its bootstrap
    # generator, for which no `MarketParameters` exists.
    resolved = parameters if isinstance(parameters, _Params) else _Params.from_market_parameters(parameters)
    return _price_with_params(resolved, values, option)


def random_parameters(rng: random.Random) -> MarketParameters:
    return MarketParameters(
        ajarai_drift=rng.uniform(-0.010, 0.020),
        ajarai_idio_std_dev=rng.uniform(0.005, 0.040),
        ajarai_rate_beta=rng.uniform(-0.150, 0.020),
        ajarai_sector_beta=rng.uniform(0.400, 1.400),
        rate_down_probability=rng.uniform(0.050, 0.250),
        rate_reversion_strength=rng.uniform(0.000, 0.250),
        rate_up_probability=rng.uniform(0.050, 0.250),
        sector_std_dev=rng.uniform(0.005, 0.030),
        theriodic_drift=rng.uniform(-0.010, 0.020),
        theriodic_idio_std_dev=rng.uniform(0.005, 0.040),
        theriodic_rate_beta=rng.uniform(-0.150, 0.020),
        theriodic_sector_beta=rng.uniform(0.400, 1.400),
    )


def random_initial_values(rng: random.Random) -> dict[int, float]:
    return {
        FED_FUNDS_RATE_UNDERLYING_ID: round(rng.randrange(4, 18) * 0.25, 2),
        AJARAI_UNDERLYING_ID: round(rng.uniform(200.0, 900.0), 2),
        THERIODIC_UNDERLYING_ID: round(rng.uniform(200.0, 900.0), 2),
    }


def underlyings(values: dict[int, float]) -> list[Underlying]:
    from bot import UNDERLYING_NAME_BY_ID

    return [
        Underlying(name=UNDERLYING_NAME_BY_ID[underlying_id], underlying_id=underlying_id, value=value)
        for underlying_id, value in values.items()
    ]


def simulate_path(parameters: MarketParameters, start: dict[int, float], num_steps: int) -> list[dict[int, float]]:
    path = [dict(start)]
    for _ in range(num_steps):
        path.append(parameters.advance_step(path[-1]))
    return path


# ---------------------------------------------------------------- 1. pricer vs Monte Carlo


def build_test_options(values: dict[int, float], rng: random.Random, count: int = 26) -> list[BinaryOption]:
    options: list[BinaryOption] = []
    for index in range(count):
        steps = index % 6  # includes zero-step options
        kind = rng.random()
        if kind < 0.30:
            legs = (OptionLeg(underlying_id=FED_FUNDS_RATE_UNDERLYING_ID, weight=1.0),)
            strike = round(values[FED_FUNDS_RATE_UNDERLYING_ID] + 0.25 * rng.randint(-2, 2), 2)
        elif kind < 0.75:
            underlying_id = rng.choice(COMPANY_IDS)
            legs = (OptionLeg(underlying_id=underlying_id, weight=1.0),)
            strike = round(values[underlying_id] * math.exp(rng.uniform(-0.15, 0.15)), 2)
        elif kind < 0.95:
            legs = (
                OptionLeg(underlying_id=AJARAI_UNDERLYING_ID, weight=1.0),
                OptionLeg(underlying_id=THERIODIC_UNDERLYING_ID, weight=-1.0),
            )
            strike = 0.0
        else:  # not promised by the problem statement, but the pricer handles it
            legs = (
                OptionLeg(underlying_id=AJARAI_UNDERLYING_ID, weight=1.0),
                OptionLeg(underlying_id=THERIODIC_UNDERLYING_ID, weight=-1.0),
            )
            strike = round(0.10 * values[THERIODIC_UNDERLYING_ID], 2)
        options.append(
            BinaryOption(legs=legs, option_id=index + 1, steps_until_expiry=steps, strike=strike)
        )
    return options


def check_theo(num_scenarios: int = 4, trials: int = 40_000) -> bool:
    print("== 1. price_option_from_parameters vs Monte Carlo ==")
    worst_error = 0.0
    worst_label = ""
    failures = 0
    for scenario in range(num_scenarios):
        rng = random.Random(1000 + scenario)
        parameters = random_parameters(rng)
        values = random_initial_values(rng)
        options = build_test_options(values, rng)
        maker = MarketMaker(underlyings(values), options, STARTING_CASH)

        by_step: dict[int, list[BinaryOption]] = defaultdict(list)
        for option in options:
            by_step[option.steps_until_expiry].append(option)
        max_steps = max(by_step)

        totals: dict[int, float] = defaultdict(float)
        random.seed(50_000 + scenario)
        for _ in range(trials):
            current = dict(values)
            for option in by_step.get(0, ()):
                totals[option.option_id] += option.expiry_valuation(current)
            for step in range(1, max_steps + 1):
                current = parameters.advance_step(current)
                for option in by_step.get(step, ()):
                    totals[option.option_id] += option.expiry_valuation(current)

        for option in options:
            empirical = totals[option.option_id] / trials
            analytic = maker.price_option_from_parameters(parameters, option)
            standard_error = math.sqrt(max(empirical * (1.0 - empirical), 1e-6) / trials)
            error = abs(analytic - empirical)
            tolerance = max(4.0 * standard_error, 0.004)
            if error > worst_error:
                worst_error = error
                worst_label = f"scenario {scenario} option {option} analytic={analytic:.4f} mc={empirical:.4f}"
            if error > tolerance:
                failures += 1
                print(f"   MISMATCH {option}: analytic={analytic:.4f} mc={empirical:.4f} tol={tolerance:.4f}")

    print(f"   worst deviation {worst_error:.4f} ({worst_label})")
    print(f"   {'PASS' if failures == 0 else f'FAIL ({failures} mismatches)'}")
    return failures == 0


# ---------------------------------------------------------------- 2. parameter recovery


def check_estimation(num_scenarios: int = 4, history_days: int = 250) -> bool:
    print("== 2. warm_up parameter recovery ==")
    ok = True
    for scenario in range(num_scenarios):
        rng = random.Random(2000 + scenario)
        parameters = random_parameters(rng)
        start = random_initial_values(rng)
        random.seed(60_000 + scenario)
        path = simulate_path(parameters, start, history_days - 1)
        history = MarketHistory(
            values_by_underlying_id={uid: tuple(day[uid] for day in path) for uid in ALL_IDS}
        )
        values = path[-1]
        options = build_test_options(values, rng, count=40)
        maker = MarketMaker(underlyings(values), options, STARTING_CASH)
        maker.warm_up(history)

        truth = _Params.from_market_parameters(parameters)
        estimate = maker._params
        deviations = [
            ("alpha_up", estimate.rate_up_intercept, truth.rate_up_intercept),
            ("alpha_down", estimate.rate_down_intercept, truth.rate_down_intercept),
            ("reversion", estimate.rate_reversion, truth.rate_reversion),
            ("rate_step", estimate.rate_step, truth.rate_step),
            ("ajr_drift", estimate.company[AJARAI_UNDERLYING_ID].drift, truth.company[AJARAI_UNDERLYING_ID].drift),
            (
                "ajr_beta",
                estimate.company[AJARAI_UNDERLYING_ID].rate_beta,
                truth.company[AJARAI_UNDERLYING_ID].rate_beta,
            ),
            (
                "ajr_vol",
                math.sqrt(estimate.company[AJARAI_UNDERLYING_ID].variance),
                math.sqrt(truth.company[AJARAI_UNDERLYING_ID].variance),
            ),
            (
                "thr_vol",
                math.sqrt(estimate.company[THERIODIC_UNDERLYING_ID].variance),
                math.sqrt(truth.company[THERIODIC_UNDERLYING_ID].variance),
            ),
            ("corr", _correlation(estimate), _correlation(truth)),
        ]
        report = "  ".join(f"{label}={got:+.4f}/{want:+.4f}" for label, got, want in deviations)

        errors = [
            abs(maker.price_option(option) - maker.price_option_from_parameters(parameters, option))
            for option in options
        ]
        mean_error = sum(errors) / len(errors)
        print(f"   scenario {scenario}: {report}")
        print(f"      price vs truth: mean |diff| {mean_error:.4f}, max {max(errors):.4f}")
        if math.sqrt(estimate.company[AJARAI_UNDERLYING_ID].variance) <= 0.0 or mean_error > 0.06:
            ok = False
            print("      FAIL: estimated prices drift too far from the true-parameter prices")
    print(f"   {'PASS' if ok else 'FAIL'}")
    return ok


def _correlation(params: _Params) -> float:
    product = math.sqrt(
        params.company[AJARAI_UNDERLYING_ID].variance * params.company[THERIODIC_UNDERLYING_ID].variance
    )
    return params.covariance / product if product > 0 else 0.0


# ---------------------------------------------------------------- 3. trading session


@dataclass
class Contract:
    option_id: int
    legs: tuple[OptionLeg, ...]
    strike: float
    expiry_day: int

    def at(self, day: int) -> BinaryOption:
        return BinaryOption(
            legs=self.legs,
            option_id=self.option_id,
            steps_until_expiry=max(self.expiry_day - day, 0),
            strike=self.strike,
        )


class NaiveMarketMaker:
    """Competitor that knows the true parameters but quotes a fixed spread around a noisy mid.

    Modelled on the graders "Fixed Width" makers, which quote a constant half-width and size
    themselves out of whatever margin they have left.
    """

    def __init__(
        self,
        label: str,
        parameters: MarketParameters,
        half_spread: float,
        noise: float,
        size: int,
        seed: int,
        account: "Account | None" = None,
    ) -> None:
        self._label = label
        self._parameters = parameters
        self._half_spread = half_spread
        self._noise = noise
        self._size = size
        self._account = account
        self._model: MarketMaker | None = None
        self._values: dict[int, float] = {}
        self._rng = random.Random(seed)  # not hash(label): string hashing is salted per process

    @property
    def name(self) -> str:
        return self._label

    def price_option(self, option: BinaryOption) -> float:
        # Price off the same estimated model as the bot, so what is being compared is the
        # quoting policy -- fixed width versus uncertainty-scaled width -- and not who has the
        # better parameters. `_model` is set to a warmed-up MarketMaker by the session builder.
        if self._model is not None:
            return self._model.price_option(option)
        base = true_price(self._parameters, self._values, option)
        return min(max(base + self._rng.gauss(0.0, self._noise), 0.0), 1.0)

    def quote(self, option: BinaryOption, counterparty_id: int) -> Quote:
        mid = self.price_option(option)
        bid = max(0, min(99, math.floor((mid - self._half_spread) * 100)))
        offer = max(bid + 1, min(100, math.ceil((mid + self._half_spread) * 100)))
        # Size against a slice of remaining margin, otherwise a fixed-width maker simply goes
        # bankrupt on day one at these balances and stops being a benchmark at all.
        budget = 0.25 * max(0.0, self._account.cash if self._account else 1e9)
        bid_size = self._size if bid == 0 else min(self._size, int(budget / (bid / 100.0)))
        offer_size = self._size if offer == 100 else min(self._size, int(budget / (1.0 - offer / 100.0)))
        return Quote(
            bid_price=bid / 100.0,
            bid_quantity=max(1, bid_size),
            offer_price=offer / 100.0,
            offer_quantity=max(1, offer_size),
        )

    def respond_to_fok(self, option: BinaryOption, fok_order: FokOrder) -> bool:
        mid = self.price_option(option)
        if fok_order.order_type == OrderType.BUY:
            return fok_order.price - mid > 0.01
        return mid - fok_order.price > 0.01

    def on_trade(self, option: BinaryOption, price: float, quantity: int, counterparty_id: int) -> None:
        pass

    def on_step_advance(self, new_underlying_state: list[Underlying], new_option_state: list[BinaryOption]) -> None:
        self._values = {u.underlying_id: u.value for u in new_underlying_state}
        if self._model is not None:
            self._model.underlying_state = new_underlying_state
            self._model.active_option_state = new_option_state
            self._model._price_cache.clear()

    def warm_up(self, market_history: MarketHistory) -> None:
        pass


# The recorded sessions show 169 distinct counterparties sending about thirteen events each, so
# identities repeat only a little. Drawing from a large pool keeps per-counterparty learning as
# hard here as it is in the real thing -- a small fixed cast made that machinery look far more
# effective than it can actually be.
COUNTERPARTY_POOL_EVENTS = 13.0
INFORMED_FRACTION = 0.15
# Measured from the recorded flow: a bot quoting a flat 0.01 / 0.99 wins 42% of every request for
# quote. On those, no competitor in the field bid above a penny or offered below ninety-nine. The
# field is therefore absent far more often than a book of tight fixed-width makers would suggest,
# and modelling it as always-present made every "quote tighter" experiment look like a loser.
UNCONTESTED_FRACTION = 0.42
# The maker's edge on a noise fill-or-kill, from the recorded flow: about zero at the median,
# positive a little over half the time, with a fat tail either way.
FOK_EDGE_MEAN = 0.01
FOK_EDGE_STD_DEV = 0.08


def counterparty_pool(rng: random.Random, expected_events: int) -> tuple[list[int], set[int]]:
    size = max(2, int(round(expected_events / COUNTERPARTY_POOL_EVENTS)))
    ids = [100_000 + rng.randrange(900_000) for _ in range(size)]
    informed = {i for i in ids if rng.random() < INFORMED_FRACTION}
    return ids, informed


NOISE_RFQ_IDS = (11, 12, 13)
INFORMED_RFQ_ID = 21
NOISE_FOK_IDS = (31, 32)
INFORMED_FOK_ID = 41


def run_session(
    seed: int,
    days: int = 45,
    zero_step_settles_next_day: bool = False,
    history_days: int = 220,
    starting_cash: float = STARTING_CASH,
    verbose: bool = False,
) -> dict[str, float]:
    rng = random.Random(seed)
    parameters = random_parameters(rng)
    random.seed(seed * 7919 + 13)
    warm_up_path = simulate_path(parameters, random_initial_values(rng), history_days - 1)
    history = MarketHistory(
        values_by_underlying_id={uid: tuple(day[uid] for day in warm_up_path) for uid in ALL_IDS}
    )
    session_path = simulate_path(parameters, warm_up_path[-1], days + 10)

    contracts: list[Contract] = []
    next_option_id = 1

    def add_contracts(day: int, values: dict[int, float], count: int) -> None:
        nonlocal next_option_id
        for _ in range(count):
            steps = rng.randint(1, 6)
            kind = rng.random()
            if kind < 0.35:
                legs = (OptionLeg(underlying_id=FED_FUNDS_RATE_UNDERLYING_ID, weight=1.0),)
                strike = round(values[FED_FUNDS_RATE_UNDERLYING_ID] + 0.25 * rng.randint(-2, 2), 2)
            elif kind < 0.80:
                underlying_id = rng.choice(COMPANY_IDS)
                legs = (OptionLeg(underlying_id=underlying_id, weight=1.0),)
                strike = round(values[underlying_id] * math.exp(rng.uniform(-0.12, 0.12)), 2)
            else:
                legs = (
                    OptionLeg(underlying_id=AJARAI_UNDERLYING_ID, weight=1.0),
                    OptionLeg(underlying_id=THERIODIC_UNDERLYING_ID, weight=-1.0),
                )
                strike = 0.0
            contracts.append(
                Contract(option_id=next_option_id, legs=legs, strike=strike, expiry_day=day + steps)
            )
            next_option_id += 1

    add_contracts(0, session_path[0], 10)
    initial_options = [contract.at(0) for contract in contracts]
    bot = MarketMaker(underlyings(session_path[0]), initial_options, starting_cash)
    competitors = [
        NaiveMarketMaker("Fixed Width 0.10", parameters, half_spread=0.10, noise=0.0, size=30, seed=seed + 1),
        NaiveMarketMaker("Fixed Width 0.05", parameters, half_spread=0.05, noise=0.0, size=30, seed=seed + 2),
    ]
    accounts = {maker.name: Account(maker=maker, cash=starting_cash) for maker in [bot, *competitors]}
    for competitor in competitors:  # let them size against their own remaining margin
        competitor._account = accounts[competitor.name]
        # Same estimated model as the bot: the comparison is of quoting policy, not of pricing.
        shared_model = MarketMaker(underlyings(session_path[0]), initial_options, starting_cash)
        shared_model.warm_up(history)
        competitor._model = shared_model
    for maker in [bot, *competitors]:
        maker.warm_up(history)
        maker.on_step_advance(underlyings(session_path[0]), initial_options)

    payoff_by_option_id: dict[int, float] = {}
    rotation = Rotation()  # one per session, so leftover lots move round the field over time

    # An exchange that settles a zero-step contract against the *following* day's values cannot
    # have retired it before those values exist, so under that convention the contract stays in
    # the book one day longer. Settling and retiring have to move together; splitting them models
    # an exchange that pays out on data it has not published yet, which is not a convention any
    # participant could be expected to track.
    settle_lag = 1 if zero_step_settles_next_day else 0

    def retire_day(contract: Contract) -> int:
        return contract.expiry_day + settle_lag

    def settlement_payoff(contract: Contract) -> float:
        return contract.at(contract.expiry_day).expiry_valuation(session_path[retire_day(contract)])

    for day in range(days):
        values = session_path[day]
        live = [contract for contract in contracts if retire_day(contract) >= day]
        if not live:
            add_contracts(day, values, 4)
            live = [contract for contract in contracts if retire_day(contract) >= day]

        for _ in range(rng.randint(2, 6)):
            _run_rfq(rng, parameters, accounts, rng.choice(live), day, values, settlement_payoff,
                     rotation=rotation)
        for _ in range(rng.randint(1, 4)):
            _run_fok(rng, parameters, accounts, rng.choice(live), day, values, settlement_payoff,
                     rotation=rotation)

        # End of day: credit expiries, then check solvency.
        expiring = [contract for contract in contracts if retire_day(contract) == day]
        for contract in expiring:
            payoff = settlement_payoff(contract)
            payoff_by_option_id[contract.option_id] = payoff
            for account in accounts.values():
                account.positions.pop(contract.option_id, None)
                account.cash += account.bought.pop(contract.option_id, 0) * payoff
                account.cash += account.sold.pop(contract.option_id, 0) * (1.0 - payoff)
        contracts = [contract for contract in contracts if retire_day(contract) > day]

        for name, account in accounts.items():
            if not account.bankrupt and account.cash < 0.0:
                account.bankrupt = True
                print(f"   !! {name} BANKRUPT on day {day} with cash {account.cash:.2f}")

        add_contracts(day + 1, session_path[day + 1], rng.randint(2, 5))
        next_options = [contract.at(day + 1) for contract in contracts if retire_day(contract) >= day + 1]
        for account in accounts.values():
            account.maker.on_step_advance(underlyings(session_path[day + 1]), next_options)

        shadow = bot.cash_balance
        actual = accounts[bot.name].cash
        # The bot credits the smaller of the two readings of an expiry, so its shadow runs at or
        # below the real balance under either settlement convention -- never above it. Crediting
        # exactly instead makes the two match to the cent, but graded worse (15.1 -> 14.3), so the
        # invariant kept here is the one the submitted bot actually maintains.
        if shadow > actual + 1e-6:
            raise AssertionError(f"day {day}: cash shadow {shadow:.2f} exceeds real balance {actual:.2f}")

    results: dict[str, float] = {}
    final_values = session_path[days]
    for name, account in accounts.items():
        # Value what is still open the same way expiry pays it out: per trade, not netted.
        mark = 0.0
        for contract in contracts:
            fair = true_price(parameters, final_values, contract.at(days))
            mark += account.bought.get(contract.option_id, 0) * fair
            mark += account.sold.get(contract.option_id, 0) * (1.0 - fair)
        results[name] = account.cash + mark - starting_cash
    results["__bankrupt__"] = 1.0 if accounts[bot.name].bankrupt else 0.0
    results["__volume__"] = float(accounts[bot.name].volume)
    results["__shadow_gap__"] = accounts[bot.name].cash - bot.cash_balance

    # Attribute the bot's PnL to each counterparty, splitting RFQ from FOK flow.
    for contract in contracts:
        payoff_by_option_id.setdefault(
            contract.option_id, true_price(parameters, final_values, contract.at(days))
        )
    attribution: dict[str, list[float]] = defaultdict(lambda: [0.0, 0.0])
    for option_id, counterparty_id, quantity, price, was_fok in accounts[bot.name].trades:
        payoff = payoff_by_option_id.get(option_id)
        if payoff is None:
            continue
        label = f"{'fok' if was_fok else 'rfq'}-{counterparty_id}"
        attribution[label][0] += quantity * (payoff - price)
        attribution[label][1] += abs(quantity)
    results["__attribution__"] = attribution  # type: ignore[assignment]
    attributed = sum(entry[0] for entry in attribution.values())
    if abs(attributed - results[bot.name]) > 1e-6:
        raise AssertionError(
            f"PnL does not reconcile: accounting says {results[bot.name]:.4f}, "
            f"sum over trades says {attributed:.4f}"
        )
    if verbose:
        print(f"   seed {seed}: " + "  ".join(f"{k}={v:+.1f}" for k, v in results.items() if k != "__attribution__"))
    return results


def _run_rfq(rng, parameters, accounts, contract, day, values, settlement_payoff, pool=None, rotation=None) -> None:
    option = contract.at(day)
    rotation = rotation if rotation is not None else Rotation()
    if pool is not None:
        ids, informed_ids = pool
        counterparty_id = rng.choice(ids)
        informed = counterparty_id in informed_ids
    else:
        informed = rng.random() < 0.15
        counterparty_id = INFORMED_RFQ_ID if informed else rng.choice(NOISE_RFQ_IDS)
    collected = collect_quotes(accounts, option, counterparty_id)
    if not collected:
        return
    if rng.random() < UNCONTESTED_FRACTION:
        # Nobody in the field puts up a real price: only the bot's own quote competes.
        collected = [
            item if item[0] == "Telescoping Theo" else (item[0], Quote(0.0, 1, 1.0, 1))
            for item in collected
        ]

    fair = true_price(parameters, values, option)
    quantity = rng.randint(1, 26)
    if informed:
        # Picks off quotes that are wrong versus the true price.
        best_bid = max(quote.bid_price for _, quote in collected)
        best_offer = min(quote.offer_price for _, quote in collected)
        if best_bid - fair >= 0.015:
            side = OrderType.SELL
        elif fair - best_offer >= 0.015:
            side = OrderType.BUY
        else:
            return
    else:
        side = OrderType.BUY if rng.random() < 0.5 else OrderType.SELL
        tolerance = rng.uniform(0.03, 0.15)  # a noise trader will pay up, but not without limit
        if side == OrderType.BUY and min(quote.offer_price for _, quote in collected) > fair + tolerance:
            return
        if side == OrderType.SELL and max(quote.bid_price for _, quote in collected) < fair - tolerance:
            return

    # An informed counterparty has no reserve price -- it already knows the quote is wrong. A noise
    # trader will pay up but not without limit. The recorded flow shows fills at 0.00 and 1.00, so
    # the limit is a property of the customer, not of the exchange.
    limit = None if informed else (
        fair + rng.uniform(0.03, 0.15) if side == OrderType.BUY else fair - rng.uniform(0.03, 0.15)
    )
    allocate_rfq(accounts, option, collected, side, quantity, counterparty_id, rotation, limit)


def _run_fok(rng, parameters, accounts, contract, day, values, settlement_payoff, pool=None, rotation=None) -> None:
    option = contract.at(day)
    rotation = rotation if rotation is not None else Rotation()
    fair = true_price(parameters, values, option)
    if pool is not None:
        ids, informed_ids = pool
        pool_id = rng.choice(ids)
        informed = pool_id in informed_ids
    else:
        pool_id = None
        informed = rng.random() < 0.15
    quantity = rng.randint(1, 30)  # measured: roughly uniform to thirty, mean thirteen
    if informed:
        # Knows the eventual payoff 75% of the time and prices to look like a small edge.
        payoff = settlement_payoff(contract)
        signal = payoff if rng.random() < 0.75 else 1.0 - payoff
        counterparty_id = pool_id if pool_id is not None else INFORMED_FOK_ID
        if signal >= 0.5:
            side, price = OrderType.BUY, min(0.99, fair + rng.uniform(0.005, 0.03))
        else:
            side, price = OrderType.SELL, max(0.01, fair - rng.uniform(0.005, 0.03))
    else:
        counterparty_id = pool_id if pool_id is not None else rng.choice(NOISE_FOK_IDS)
        # Price the order near fair rather than a guaranteed distance the wrong side of it.
        # Measured against the recorded flow, the edge on taking one of these is about zero at the
        # median and positive barely over half the time. Handing the maker three to fifteen cents
        # every time, as this used to, makes fill-or-kill flow free money and any setting that
        # accepts more of it look good -- which is exactly where this harness misled.
        edge = rng.gauss(FOK_EDGE_MEAN, FOK_EDGE_STD_DEV)
        if rng.random() < 0.5:
            side, price = OrderType.BUY, min(0.99, max(0.01, fair + edge))
        else:
            side, price = OrderType.SELL, min(0.99, max(0.01, fair - edge))

    order = FokOrder(
        counterparty_id=counterparty_id,
        option_id=option.option_id,
        order_type=side,
        price=round(price, 2),
        quantity=quantity,
    )
    allocate_fok(accounts, option, order, rotation)


def check_sessions(num_sessions: int = 12) -> bool:
    print("== 3. trading sessions ==")
    ok = True
    wins = 0
    total = 0.0
    combined: dict[str, list[float]] = defaultdict(lambda: [0.0, 0.0])
    for index in range(num_sessions):
        results = run_session(seed=3000 + index)
        for label, (pnl_value, contracts_traded) in results["__attribution__"].items():  # type: ignore[attr-defined]
            combined[label][0] += pnl_value
            combined[label][1] += contracts_traded
        pnl = results["Telescoping Theo"]
        rivals = {k: v for k, v in results.items() if not k.startswith("__") and k != "Telescoping Theo"}
        best_rival = max(rivals.values())
        total += pnl
        if pnl >= best_rival:
            wins += 1
        flag = "BANKRUPT" if results["__bankrupt__"] else ""
        print(
            f"   seed {3000 + index}: bot {pnl:+8.1f}  "
            + "  ".join(f"{name} {value:+8.1f}" for name, value in rivals.items())
            + f"   volume {results['__volume__']:.0f}  shadow gap {results['__shadow_gap__']:+.1f} {flag}"
        )
        if results["__bankrupt__"]:
            ok = False
        if pnl < 0:
            print("      note: negative PnL on this seed")
    print(f"   mean PnL {total / num_sessions:+.1f}, best of book in {wins}/{num_sessions} sessions")
    print("   PnL by flow source (total over all sessions):")
    for label in sorted(combined, key=lambda key: combined[key][0]):
        pnl_value, contracts_traded = combined[label]
        per_contract = pnl_value / contracts_traded if contracts_traded else 0.0
        print(f"      {label:>10}: {pnl_value:+9.1f} over {contracts_traded:7.0f} contracts ({per_contract:+.4f}/ct)")
    print(f"   {'PASS' if ok else 'FAIL (bankruptcy)'}")
    return ok


# ---------------------------------------------------------------- 4. degenerate inputs


def check_edge_cases() -> bool:
    print("== 4. degenerate inputs ==")
    ok = True
    rng = random.Random(99)
    values = random_initial_values(rng)
    parameters = random_parameters(rng)
    options = build_test_options(values, rng)

    # No warm-up at all: must still quote legally and price in range.
    maker = MarketMaker(underlyings(values), options, STARTING_CASH)
    for option in options:
        price = maker.price_option(option)
        assert 0.0 <= price <= 1.0, price
        quote = maker.quote(option, 7)
        assert 0.0 <= quote.bid_price < quote.offer_price <= 1.0
    print("   no warm_up: prices in range, quotes legal")

    # One-day, empty, and pinned-at-zero histories.
    for label, history in (
        ("single day", MarketHistory({uid: (values[uid],) for uid in ALL_IDS})),
        ("empty", MarketHistory({})),
        (
            "rate pinned at zero",
            MarketHistory(
                {
                    FED_FUNDS_RATE_UNDERLYING_ID: tuple(0.0 for _ in range(60)),
                    AJARAI_UNDERLYING_ID: tuple(100.0 + 0.5 * index for index in range(60)),
                    THERIODIC_UNDERLYING_ID: tuple(100.0 - 0.2 * index for index in range(60)),
                }
            ),
        ),
        (
            "flat values",
            MarketHistory({uid: tuple(values[uid] for _ in range(60)) for uid in ALL_IDS}),
        ),
    ):
        maker = MarketMaker(underlyings(values), options, STARTING_CASH)
        maker.warm_up(history)
        for option in options:
            assert 0.0 <= maker.price_option(option) <= 1.0
            assert 0.0 <= maker.price_option_from_parameters(parameters, option) <= 1.0
            quote = maker.quote(option, 7)
            assert 0.0 <= quote.bid_price < quote.offer_price <= 1.0
            assert quote.bid_quantity > 0 and quote.offer_quantity > 0
        print(f"   {label} history: quotes legal")

    # Contract shapes and balances the graded cases never contain. Round one only ever shows unit
    # leg weights, one-to-five-step expiries, books of three to ten, and balances of 10/20/40, so
    # nothing outside that has been exercised by a score. These lock in that it stays legal there.
    outside_envelope = [
        ("fractional leg weights", (OptionLeg(underlying_id=AJARAI_UNDERLYING_ID, weight=0.5),
                                    OptionLeg(underlying_id=THERIODIC_UNDERLYING_ID, weight=0.5)), 3),
        ("a rate leg mixed with a company leg", (OptionLeg(underlying_id=FED_FUNDS_RATE_UNDERLYING_ID, weight=1.0),
                                                 OptionLeg(underlying_id=AJARAI_UNDERLYING_ID, weight=-0.001)), 3),
        ("a zero-step option in the live book", (OptionLeg(underlying_id=AJARAI_UNDERLYING_ID, weight=1.0),), 0),
        ("a twenty-step option", (OptionLeg(underlying_id=THERIODIC_UNDERLYING_ID, weight=1.0),), 20),
    ]
    history = MarketHistory({uid: tuple(values[uid] for _ in range(30)) for uid in ALL_IDS})
    for label, legs, steps in outside_envelope:
        strike = 0.0 if len(legs) > 1 else round(values[legs[0].underlying_id] * 1.02, 2)
        option = BinaryOption(legs=legs, option_id=99, steps_until_expiry=steps, strike=strike)
        for cash in (1.0, 5.0, 250.0, 5000.0):
            maker = MarketMaker(underlyings(values), [option], cash)  # a book of exactly one
            maker.warm_up(history)
            price = maker.price_option(option)
            assert 0.0 <= price <= 1.0, (label, cash, price)
            quote = maker.quote(option, 7)
            assert 0.0 <= quote.bid_price < quote.offer_price <= 1.0, (label, cash, quote)
            assert quote.bid_quantity > 0 and quote.offer_quantity > 0, (label, cash, quote)
            # Never show a market that would lose money on its own valuation.
            assert quote.bid_price <= price + 1e-9 or steps == 0, (label, cash, quote, price)
            assert quote.offer_price >= price - 1e-9 or steps == 0, (label, cash, quote, price)
        print(f"   {label}: legal at every balance")

    # Enormous fill-or-kill orders must never be accepted beyond the cash buffer.
    maker = MarketMaker(underlyings(values), options, STARTING_CASH)
    maker.warm_up(MarketHistory({uid: tuple(values[uid] for _ in range(60)) for uid in ALL_IDS}))
    accepted_margin = 0.0
    for option in options:
        for side in (OrderType.BUY, OrderType.SELL):
            order = FokOrder(
                counterparty_id=1, option_id=option.option_id, order_type=side, price=0.5, quantity=100_000
            )
            if maker.respond_to_fok(option, order):
                accepted_margin += 50_000.0
    if accepted_margin > 0:
        ok = False
        print(f"   FAIL: accepted {accepted_margin:.0f} of margin on 100k-lot orders")
    else:
        print("   huge FOK orders: all declined")

    # Stress the cash model: thin balances, a long session, late settlement, a short warm-up.
    for label, kwargs in (
        ("zero-step settles next day", {"zero_step_settles_next_day": True}),
        ("short history", {"history_days": 30}),
        ("tiny cash (10)", {"starting_cash": 10.0}),
        ("small cash (40)", {"starting_cash": 40.0}),
        ("long session (200 days)", {"days": 200}),
        ("long session, tiny cash", {"days": 200, "starting_cash": 10.0}),
    ):
        for seed in (777, 778):
            arguments = {"days": 35, **kwargs}
            results = run_session(seed=seed, **arguments)
            status = "BANKRUPT" if results["__bankrupt__"] else "solvent"
            print(
                f"   {label} [seed {seed}]: bot {results['Telescoping Theo']:+.1f} "
                f"volume {results['__volume__']:.0f} ({status})"
            )
            if results["__bankrupt__"]:
                ok = False

    print(f"   {'PASS' if ok else 'FAIL'}")
    return ok


def check_flipped_fok_convention() -> bool:
    """If `order_type` meant our own side, the bot should notice and stop bleeding."""
    print("== 5. reversed FOK convention ==")
    rng = random.Random(5)
    values = random_initial_values(rng)
    parameters = random_parameters(rng)
    random.seed(4242)
    path = simulate_path(parameters, values, 120)
    history = MarketHistory({uid: tuple(day[uid] for day in path) for uid in ALL_IDS})
    values = path[-1]
    options = build_test_options(values, rng, count=12)
    maker = MarketMaker(underlyings(values), options, STARTING_CASH)
    maker.warm_up(history)

    accepted = 0
    for round_index in range(40):
        option = options[round_index % len(options)]
        if option.steps_until_expiry == 0:
            continue
        fair = maker.price_option(option)
        side = OrderType.BUY if round_index % 2 == 0 else OrderType.SELL
        price = round(min(0.99, fair + 0.12), 2) if side == OrderType.BUY else round(max(0.01, fair - 0.12), 2)
        order = FokOrder(counterparty_id=9, option_id=option.option_id, order_type=side, price=price, quantity=5)
        if maker.respond_to_fok(option, order):
            accepted += 1
            # Report the fill with the OPPOSITE sign to what the bot expects.
            quantity = 5 if side == OrderType.BUY else -5
            maker.on_trade(option, price, quantity, 9)
    flipped = maker._fok_side_flipped
    print(f"   accepted {accepted} orders, convention flipped: {flipped}")
    print(f"   {'PASS' if flipped else 'FAIL (never noticed)'}")
    return flipped


def main() -> int:
    if sys.version_info < (3, 11):
        print(f"needs Python 3.11+ for StrEnum, got {sys.version_info.major}.{sys.version_info.minor}")
        return 2
    which = sys.argv[1] if len(sys.argv) > 1 else "all"
    results = []
    if which in ("all", "theo"):
        results.append(check_theo())
    if which in ("all", "estimate"):
        results.append(check_estimation())
    if which in ("all", "session"):
        results.append(check_sessions())
    if which in ("all", "edge"):
        results.append(check_edge_cases())
        results.append(check_flipped_fok_convention())
    print("\n" + ("ALL CHECKS PASSED" if all(results) else "SOME CHECKS FAILED"))
    return 0 if all(results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
